name: Close inactive issues / prs
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v7
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 14
          days-before-pr-stale: 60
          days-before-pr-close: 14
          operations-per-run: 1000
          stale-issue-label: "Stale"
          stale-pr-label: "Stale"
          stale-issue-message: >
            This issue is stale because it has been open for 60 days with no activity. It will be closed if no further action occurs in 14 days.
          close-issue-message: |
            We are closing this issue because it has been inactive for a few months.
            This probably means that it is not reproducible or it has been fixed in a newer version.
            If it’s an enhancement and hasn’t been taken on since it was submitted, then it seems other issues have taken priority.

            If you still encounter this issue with the latest stable version, please reopen using the issue template. You can also contribute directly by submitting a pull request– see the [CONTRIBUTING.md](https://github.com/Shopify/shopify_app/blob/main/CONTRIBUTING.md) file for guidelines

            Thank you!
          stale-pr-message: >
            This pull request is stale because it has been open for 60 days with no activity. It will be closed if no further action occurs in 14 days.
          close-pr-message: |
            We are closing this pull request because it has been inactive for a few months.
            This probably means that it is not reproducible or it has been fixed in a newer version.
            If it’s an enhancement and hasn’t been taken on since it was submitted, then it seems other issues have taken priority.

            If you still encounter this pull request with the latest stable version, please reopen using the pull request template. You can also contribute directly by submitting a pull request– see the [CONTRIBUTING.md](https://github.com/Shopify/shopify_app/blob/main/CONTRIBUTING.md) file for guidelines

            Thank you!
          repo-token: ${{ github.token }}
          close-issue-reason: "not_planned"
